"""initial_schema

Revision ID: dc6609c6b0a2
Revises: 
Create Date: 2026-08-24 08:38:07.305235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dc6609c6b0a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coach_athlete_assignments', 'status',
               existing_type=mysql.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('coach_athlete_assignments', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('notifications', 'is_read',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=True)
    op.alter_column('notifications', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('team_athletes', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('teams', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'user_roles', ['user_id', 'role_id'])
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('webhooks', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=True)
    op.alter_column('webhooks', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('webhooks', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               server_default=sa.text('now()'),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webhooks', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('webhooks', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('webhooks', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               existing_nullable=True)
    op.drop_constraint(None, 'user_roles', type_='unique')
    op.alter_column('teams', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('team_athletes', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('notifications', 'is_read',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=True)
    op.alter_column('coach_athlete_assignments', 'created_at',
               existing_type=sa.DateTime(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('coach_athlete_assignments', 'status',
               existing_type=mysql.VARCHAR(length=50),
               server_default=sa.text("'pending'"),
               existing_nullable=True)
    # ### end Alembic commands ###
